version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    container_name: php_app
    volumes:
      - ./app:/var/www/html
      - ./scripts:/var/www/html/scripts
      - ./config:/var/www/html/config
    depends_on:
      - postgres
      - redis


  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  postgres:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: always

volumes:
  pgdata:
